name: Redeploy project
on:
   pull_request:
    branches: ['release', 'main']

jobs:
  redeploy-project:
    name: Redeploy project
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}prackicum-server-code-alchemists/server:latest

      - name: Connect to VPS and redeploy project with new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: touch test.tsx
